# Generated by Django 2.0.2 on 2018-02-09 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_', '0005_merge_20180209_1110'),
        ('warehouse_', '0002_warehouse_warehousehasitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousehasitem',
            name='item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item_.Item'),
        ),
    ]
