# Generated by Django 2.0.2 on 2018-02-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_', '0003_warehousehasitem_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehousehasitem',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='warehousehasitem',
            old_name='warehouse_id',
            new_name='warehouse',
        ),
    ]
