# Generated by Django 2.0.2 on 2018-02-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategorie',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=45)),
                ('has_kardex', models.IntegerField()),
            ],
        ),
    ]
