# Generated by Django 2.0.2 on 2018-02-09 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExistenceType',
            fields=[
                ('existence_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategorie',
            fields=[
                ('item_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=45)),
                ('has_kardex', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_.ItemCategorie'),
        ),
        migrations.AddField(
            model_name='item',
            name='existence_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_.ExistenceType'),
        ),
    ]
