# Generated by Django 2.0.2 on 2018-02-09 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistenceType',
            fields=[
                ('existence_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=48)),
            ],
        ),
        migrations.RenameField(
            model_name='itemcategorie',
            old_name='item_name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='itemcategorie',
            old_name='item_id',
            new_name='item_category_id',
        ),
        migrations.AddField(
            model_name='item',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_.ItemCategorie'),
        ),
        migrations.AddField(
            model_name='item',
            name='existence_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_.ExistenceType'),
        ),
    ]
