# Generated by Django 2.0.2 on 2018-02-09 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistenceType',
            fields=[
                ('existence_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=48)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_.ItemCategorie')),
                ('existence_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_.ExistenceType')),
            ],
        ),
    ]
