# Generated by Django 2.0.2 on 2018-02-09 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_', '0002_existencetype_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcategorie',
            old_name='item_name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='itemcategorie',
            old_name='item_id',
            new_name='item_category_id',
        ),
    ]
