# Generated by Django 2.0.2 on 2018-02-09 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_', '0003_auto_20180208_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='existence_type',
        ),
        migrations.RenameField(
            model_name='itemcategorie',
            old_name='item_category_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='itemcategorie',
            old_name='category_name',
            new_name='item_name',
        ),
        migrations.DeleteModel(
            name='ExistenceType',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
