# Generated by Django 2.0.2 on 2018-02-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_', '0002_auto_20180209_0144'),
        ('item_', '0004_auto_20180209_0039'),
    ]

    operations = [
    ]
