# Generated by Django 2.0.2 on 2018-02-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='unit_type',
            fields=[
                ('id_unit_type', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
