# Generated by Django 2.0.2 on 2018-02-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit_type',
            name='campo_sebasssssss',
            field=models.CharField(default='sebas ves que si sale', max_length=100),
        ),
    ]
