# Generated by Django 2.0.2 on 2018-02-08 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit_type', '0002_unit_type_campo_sebasssssss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit_type',
            name='campo_sebasssssss',
        ),
    ]
