# Generated by Django 2.0.2 on 2018-02-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='voucher_type',
            fields=[
                ('id_voucher_type', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
            ],
        ),
    ]
